
business_type_dict = dict{'NA':'Not a third space',
 ',':'1', #not a NAIC number
 'Rental': 'Third space',
 'Retail Sales of Perishable Foods': 'Third space',
 'Retail Sale of Tobacco': 'Third space',
 'Vacant Residential Property / Lot': 'Not a third space',
 'Consumption of Liquor on Premises': 'Third space',
 'Food Preparing and Serving': 'Third space',
 'Apartment House': 'Third space',
 'Tavern - Consumption of Liquor on Premise': 'Third space',
 'Dumpster License - Private Property': 'Not a third space',
 'Retail Sales of Packaged Liquor': 'Third space',
 'Commercial/Industrial Space  Rental': 'Third space',
 'Contracting – Building': 'Unknown',
 'Scales and Scanners': 'Unknown',
 'Wholesale Food Sales': 'Third space',
 'Special Event Food': 'Third space',
 'Business Office': 'Third space',
 'Other Home Based Businesses': 'Unknown',
 'Not-For-Profit Selling Raffles for Prizes of $50 or More': 'Third space',
 'Preparation of Food and Dining on Premise With Seating': 'Third space',
 'Provide Parking Spaces For a Fee - Available and Advertised to the Public': 'Third space',
 'Contracting - Misc.': 'Not a third space',
 'Hair Services': 'Third space',
 'Miscellaneous Commercial Services': 'Unknown',
 'Retail Sales': 'Third space',
 'Provides Onsite Amusement or Entertainment': 'Third space',
 'Operation of a Fuel Filling Station': 'Not a third space',
 'Food Preparing and Serving (30+ SEATS)': 'Third space',
 'Sale of Liquor Outdoors on Private Property': 'Not a third space',
 'Consulting': 'Unknown',
 'Peddler- Retail Sales of General Merchandise, Whole Uncut Fruits/Vegetables, Flowers, Moving Along the Public Way': 'Third space',
 'Valet Parking Operator':'Not a third space',
 'Contracting – Electrical': 'Not a third space',
 'Food Establishment, Retail Permanent Location':'Third space',
 'Debt Collecting - Administrative Commercial Office': 'Not a third space',
 'Hazardous Materials': 'Not a third space',
 'Motor Vehicle Repair -  Engine and Transmission Work':'Not a third space',
 'Motor Vehicle Repair / Retail Mobile Dispensing':'Not a third space',
 'Retail Sales of Clothing / Accessories / Shoes': 'Third space',
 'Markets / Promotes Pharmaceuticals to Health Care Professionals and Conducts Business for More than 15 Calendar Days per Year': 'Not a third space',
 'Administrative Commercial Office':'Unknown',
 'Retail Sales of General Merchandise':'Unknown',
 'Sale of Food Prepared Onsite With Dining Area': 'Third space',
 'Restaurant & Ready to Eat Foods': 'Third space',
 'Buying and Reselling of Used Valuable Objects':'Third space',
 'Internet Sales/Service': 'Not a third space',
 'General Services – Other': 'Unknown',
 'Dumpster License - Public ROW': 'Not a third space',
 'Towing': 'Not a third space',
 'Sale of Liquor Until 4am, Monday - Saturday and 5am on Sunday': 'Not a third space',
 'Street Performer, Moving Along the Public Way': 'Third space',
 'Real Estate Agent': 'Not a third space',
 'Miscellaneous Manufacturing': 'Unknown',
 'Massage Establishment':'Third space',
 'Storage or Use of Hazardous Materials': 'Not a third spcae',
 'Child Care Facility': 'Third space',
 '5 Day Single - Special Event Food': 'Third space',
 'Barber/Beauty (booth)': 'Third space',
 'Tax Preparation Services': 'Not a third space',
 'Special Event Beer & Wine': 'Third space',
 'Barber/Beauty Shop Owner': 'Third space',
 'Sale of Food Prepared Onsite Without Dining Area':'Third space',
 'Nail Services': 'Third space',
 'Contracting – Plumbing': 'Not a third space',
 'Catering of Liquor To Events': 'Not a third space',
 'Acquisition and Improvement of Land/Residential Buildings': 'Not a third space',
 'Provide Parking Spaces For a Fee - to Residents, Tenants, Users, Employees and/or Guests (Not Available or Advertised to the Public)':'Third space',
 'Food Retail Store': 'Third space',
 'Dry Cleaning - Drop Off Location': 'Third space',
 'Retail Sales of General Merchandise and Non-Perishable Food': 'Third space',
 'Attorney': 'Not a third space',
 'Handyman': 'Not a third space',
 'Heating, Ventilation and Air Conditioning Services - Commercial | Heating, Ventilation and Air Conditioning Services - Residential':'Not a third space',
 'Private Scavenger - Vehicle':'Unknown',
 'Janitorial Service': 'Not a third space',
 'Amusement':'Unknown',
 'Contracting – Roofing': 'Not a third space',
 'Handbill Distribution': 'Not a third space',
 'Motor Vehicle Repair - Engine and Body Work': 'Not a third space',
 'Contracting – Engineering': 'Not a third space',
 'Retail Sales of Tobacco Products': 'Third space',
 'Shared Kitchen User - Long Term': 'Unknown',
 'Restaurant & Ready to Eat Foods with Alcohol':'Third space',
 'Direct Sales Product Distribution': 'Not a third space',
 'Mobile Services - Misc.': 'Unknown',
 'Supervision of, and Care for, Children 0-6 Years of Age, During the Day between 6am-9pm': 'Not a third space',
 'Consumption of Liquor on Premises, Not for Profit': 'Third space',
 'Real Estate Office': 'Not a third space',
 'Mobile Food Vending': 'Third space',
 'Financial Services': 'Not a third space',
 'Gardening/Landscape Maint.': 'Not a third space',
 'Supervision of, and Care for, Children 2-6 Years of Age, During the Day between 6am-9pm': 'Not a third space',
 'Retail Sales of Cell Phones and Accessories': 'Not a third space',
 'Massage/Body Wrap Tech': 'Third space',
 'Drafting/Graphics Design': 'Unknown',
 'Retail Sales of Jewelry and Jewelry Repair' : 'Unknown',
 'Home Repair Services (Home Based Business)': 'Not a third space',
 'Employee of a Wrecking/Demolitio/Fireworks Contractor (Cert. of Fitness)' : 'Not a third space',
 'Organizer of Vendors That Sell for Retail at a Trade Show, Exhibition or Convention': 'Third space',
 'Peddler - Retail Sales of General Merchandise, Whole Uncut Fruits/Vegetables, Flowers, Moving Along the Public Way (Special)':'Third space',
 'Sales of Packaged Frozen Desserts From a Non-Motorized Cart (Mobile Desserts Vendor)':'Third space',
 'Instructor/Personal Trainer': 'Not a third space',
 'Miscellaneous Wholesale': 'Unknown',
 'Medical Office/Clinic':'Not a third space',
 'Food Establishment, Retail Perm Location (Large)': 'Third space',
 'Miscellaneous Personal Services': 'Unknown',
 'Heating, Ventilation and Air Conditioning Services - Residential': 'Not a third space',
 'Manufacturing': 'Unknown',
 'Sidewalk Cafe': 'Third space',
 'Physician/Surgeon': 'Not a third space',
 'Auto Repair – General': 'Not a third space',
 'Advertising / Marketing / Sales Office': 'Not a third space',
 'High Rise':'Unknown',
 'Computer Programming/Consulting': 'Not a third space',
 'Online Sales (Home Based Business)':'Not a third space',
 'Hotel - 7 or More Sleeping Rooms': 'Third space',
 'Wholesale': 'Unknown',
 'Heating, Ventilation and Air Conditioning Services - Commercial':'Not a third space',
 'Sidewalk Cafe/Streetery (Temporary)': 'Third space',
 'Promoting': 'Unknown',
 'Public Place of Amusement, Provides Entertainment, Room Rentals and Charges a Fee': 'Third space',
 'Retail Sales of General Merchandise and Non-Perishable Food | Retail Sales of Perishable Foods': 'Unknown',
 'Professional Consulting (Home Based Business)': 'Not a third space',
 'Sale of Furniture': 'Third space',
 'Pledging of Property for Money (Pawn)': 'Third space',
 'Preparation of License, Certificate or Permit Applications for Compensation': 'Not a third space',
 'Catering/Party Consulting': 'Not a third space',
 'Food Retail Store w/ Alcohol': 'Third space',
 'Nails/Manicure Shop': 'Third space',
 'Public Garage / Parking Lot': 'Third space',
 'Professional Services - Other': 'Unknown',
 'Wholesale Tobacco Product Sales': 'Not a third space',
 'Photography – Freelance': 'Not a third space',
 'Sales / Rental / Lease of Motorized Vehicles': 'Not a third space',
 'Financial Services – Other':'Not a third space',
 'Junk Peddler': 'Unknown',
 'Marketing': 'Unknown',
 'Retail Sales of Flowers': 'Third space',
 'Travel Services': 'Not a third space ',
 'Medical Cannabis Dispensary': 'Not a third space',
 'Rentals - Misc.': 'Not a third space',
 'Outdoor Advertising Sign': 'Not a third space',
 'Motor Vehicle Repair - No Engine Work/No Body Work': 'Not a third space',
 'Food Estab, Retail Non-Permanent Location (Annual)': 'Third space',
 'Boat Cleaning/Repair (Mobile Service)': 'Not a third space',
 'Laundromat - Self Service': 'Third space',
 }
